// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKvIDd6pxbzcXPjubiUVVMPew1Z6MT-Ys',
    appId: '1:358036820447:web:5ffc82861b1048c470746a',
    messagingSenderId: '358036820447',
    projectId: 'flash-chat-a66ae',
    authDomain: 'flash-chat-a66ae.firebaseapp.com',
    storageBucket: 'flash-chat-a66ae.firebasestorage.app',
    measurementId: 'G-PF6V89M8D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBrdS3lV0e0TQcmJZP24ijvFeG0W0JmJE',
    appId: '1:358036820447:android:a8739da91a123cfc70746a',
    messagingSenderId: '358036820447',
    projectId: 'flash-chat-a66ae',
    storageBucket: 'flash-chat-a66ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChLjTdnjRhkaVymna-pD5LKKEQj3ypB00',
    appId: '1:358036820447:ios:08ac6804b65ab08970746a',
    messagingSenderId: '358036820447',
    projectId: 'flash-chat-a66ae',
    storageBucket: 'flash-chat-a66ae.firebasestorage.app',
    iosBundleId: 'com.example.flashChatFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKvIDd6pxbzcXPjubiUVVMPew1Z6MT-Ys',
    appId: '1:358036820447:web:35f0beeab920094870746a',
    messagingSenderId: '358036820447',
    projectId: 'flash-chat-a66ae',
    authDomain: 'flash-chat-a66ae.firebaseapp.com',
    storageBucket: 'flash-chat-a66ae.firebasestorage.app',
    measurementId: 'G-XV9D7S95WW',
  );
}
